const ONSEN_DATA = [
  // ===== 🌨️ 北海道 =====
  {key:'北海道登別温泉',pref:'北海道',name:'登別温泉',region:'🌨️ 北海道',stars:3,starStr:'⭐⭐⭐',dayBath:'登別温泉郷滝乃家、祝いの宿登別グランドホテル、第一滝本館',milky:true,mixed:false},
  {key:'北海道湯の川温泉',pref:'北海道',name:'湯の川温泉',region:'🌨️ 北海道',stars:3,starStr:'⭐⭐⭐',dayBath:'湯の川温泉 ホテル万葉、湯の川温泉 温泉ホテル',milky:false,mixed:false},
  {key:'北海道定山渓温泉',pref:'北海道',name:'定山渓温泉',region:'🌨️ 北海道',stars:3,starStr:'⭐⭐⭐',dayBath:'定山渓グランドホテル瑞苑、定山渓鶴雅リゾート',milky:false,mixed:false},
  {key:'北海道ニセコ温泉',pref:'北海道',name:'ニセコ温泉',region:'🌨️ 北海道',stars:3,starStr:'⭐⭐⭐',dayBath:'ニセコパークテラスホテル、グラフィア',milky:true,mixed:false},
  {key:'北海道網走温泉',pref:'北海道',name:'網走温泉',region:'🌨️ 北海道',stars:3,starStr:'⭐⭐⭐',dayBath:'ホテル網走、能登屋ホテル',milky:false,mixed:false},
  {key:'北海道美幌峠温泉',pref:'北海道',name:'美幌峠温泉',region:'🌨️ 北海道',stars:3,starStr:'⭐⭐⭐',dayBath:'望湖台温泉',milky:false,mixed:false},
  {key:'北海道阿寒湖温泉',pref:'北海道',name:'阿寒湖温泉',region:'🌨️ 北海道',stars:3,starStr:'⭐⭐⭐',dayBath:'あかん遊久の里鶴雅、鄙の座',milky:false,mixed:false},
  {key:'北海道屈斜路温泉',pref:'北海道',name:'屈斜路温泉',region:'🌨️ 北海道',stars:3,starStr:'⭐⭐⭐',dayBath:'レイクホテル屈斜路、湯元鶴雅',milky:false,mixed:false},
  {key:'北海道羅臼温泉',pref:'北海道',name:'羅臼温泉',region:'🌨️ 北海道',stars:3,starStr:'⭐⭐⭐',dayBath:'熊の湯（無料）、旅館 まるみ',milky:true,mixed:false},
  // ===== 🍎 東北 =====
  {key:'青森県酸ヶ湯温泉',pref:'青森県',name:'酸ヶ湯温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'酸ヶ湯温泉旅館、八甲田ホテル',milky:true,mixed:true},
  {key:'青森県浅虫温泉',pref:'青森県',name:'浅虫温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'浅虫温泉 旅館南宛、旅館大佛',milky:false,mixed:false},
  {key:'青森県大鰐温泉',pref:'青森県',name:'大鰐温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'すきや亭、星野リゾート 青森屋',milky:false,mixed:false},
  {key:'青森県谷地温泉',pref:'青森県',name:'谷地温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'谷地温泉（日本三大秘湯）',milky:true,mixed:false},
  {key:'青森県八甲田温泉',pref:'青森県',name:'八甲田温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'酸ヶ湯温泉旅館',milky:true,mixed:false},
  {key:'青森県嶽温泉',pref:'青森県',name:'嶽温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'山のホテル',milky:true,mixed:false},
  {key:'青森県下風呂温泉',pref:'青森県',name:'下風呂温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'新湯旅館、浜館',milky:true,mixed:false},
  {key:'青森県恐山温泉',pref:'青森県',name:'恐山温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'恐山菩提寺（無料）',milky:true,mixed:false},
  {key:'岩手県繫温泉',pref:'岩手県',name:'繫温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'別邸 山の抄、旅館田中',milky:false,mixed:false},
  {key:'岩手県花巻温泉郷',pref:'岩手県',name:'花巻温泉郷',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'花巻温泉ホテルさか田',milky:false,mixed:false},
  {key:'岩手県金田一温泉',pref:'岩手県',name:'金田一温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'旅館 千葉旅館、旅館 佳松',milky:false,mixed:false},
  {key:'岩手県つなぎ温泉',pref:'岩手県',name:'つなぎ温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'ホテル紫苑',milky:false,mixed:false},
  {key:'岩手県藤七温泉',pref:'岩手県',name:'藤七温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'彩雲荘（東北最高所・泥パック混浴）',milky:true,mixed:true},
  {key:'岩手県松川温泉',pref:'岩手県',name:'松川温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'峡雲荘、松楓荘',milky:true,mixed:false},
  {key:'岩手県須川温泉',pref:'岩手県',name:'須川温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'須川高原温泉',milky:true,mixed:false},
  {key:'岩手県大沢温泉',pref:'岩手県',name:'大沢温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'大沢温泉 湯治屋（宮沢賢治ゆかりの混浴露天）',milky:false,mixed:true},
  {key:'宮城県鳴子温泉',pref:'宮城県',name:'鳴子温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'鳴子温泉 旅館あづま、大沼旅館',milky:true,mixed:false},
  {key:'宮城県松島温泉',pref:'宮城県',name:'松島温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'ホテル海風土',milky:false,mixed:false},
  {key:'宮城県作並温泉',pref:'宮城県',name:'作並温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'ホテルニュー水戸屋、最上屋旅館',milky:false,mixed:false},
  {key:'秋田県玉川温泉',pref:'秋田県',name:'玉川温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'旅館田中',milky:false,mixed:false},
  {key:'秋田県乳頭温泉郷',pref:'秋田県',name:'乳頭温泉郷',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'鶴の湯（600円）、黒湯、蟹場温泉',milky:true,mixed:true},
  {key:'秋田県後生掛温泉',pref:'秋田県',name:'後生掛温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'後生掛温泉（600円）',milky:true,mixed:true},
  {key:'秋田県蒸の湯温泉',pref:'秋田県',name:'蒸の湯温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'ふけの湯温泉（700円）',milky:true,mixed:false},
  {key:'秋田県泥湯温泉',pref:'秋田県',name:'泥湯温泉',region:'🍎 東北',stars:3,starStr:'⭐⭐⭐',dayBath:'奥山旅館',milky:false,mixed:false},
  {key:'山形県蔵王温泉',pref:'山形県',name:'蔵王温泉',region:'🍎 東北',stars:2,starStr:'⭐⭐',dayBath:'蔵王国際ホテル、深山荘高見屋',milky:true,mixed:true},
  {key:'山形県肘折温泉',pref:'山形県',name:'肘折温泉',region:'🍎 東北',stars:2,starStr:'⭐⭐',dayBath:'旅館松葉、肘折温泉 大浴場',milky:false,mixed:false},
  {key:'山形県天童温泉',pref:'山形県',name:'天童温泉',region:'🍎 東北',stars:2,starStr:'⭐⭐',dayBath:'ホテル天童、旅館 こんや',milky:false,mixed:false},
  {key:'山形県姥湯温泉',pref:'山形県',name:'姥湯温泉',region:'🍎 東北',stars:2,starStr:'⭐⭐',dayBath:'枡形屋（要予約・絶壁囲む秘湯）',milky:true,mixed:true},
  {key:'山形県滑川温泉',pref:'山形県',name:'滑川温泉',region:'🍎 東北',stars:2,starStr:'⭐⭐',dayBath:'滑川温泉 福島屋',milky:true,mixed:false},
  {key:'福島県磐梯熱海温泉',pref:'福島県',name:'磐梯熱海温泉',region:'🍎 東北',stars:2,starStr:'⭐⭐',dayBath:'ホテルハイマート',milky:false,mixed:false},
  {key:'福島県土湯温泉',pref:'福島県',name:'土湯温泉',region:'🍎 東北',stars:2,starStr:'⭐⭐',dayBath:'玉子湯、あづま',milky:false,mixed:false},
  {key:'福島県会津東山温泉',pref:'福島県',name:'会津東山温泉',region:'🍎 東北',stars:2,starStr:'⭐⭐',dayBath:'新滝、ホテル会津',milky:false,mixed:false},
  {key:'福島県飯坂温泉',pref:'福島県',name:'飯坂温泉',region:'🍎 東北',stars:2,starStr:'⭐⭐',dayBath:'旅館大亀、ホテル福の湯',milky:false,mixed:false},
  {key:'福島県いわき湯本温泉',pref:'福島県',name:'いわき湯本温泉',region:'🍎 東北',stars:2,starStr:'⭐⭐',dayBath:'スパリゾート ハワイアンズ',milky:false,mixed:false},
  {key:'福島県高湯温泉',pref:'福島県',name:'高湯温泉',region:'🍎 東北',stars:2,starStr:'⭐⭐',dayBath:'旅館 玉子湯（700円）、吾妻屋',milky:true,mixed:false},
  {key:'福島県野地温泉',pref:'福島県',name:'野地温泉',region:'🍎 東北',stars:2,starStr:'⭐⭐',dayBath:'野地温泉ホテル',milky:true,mixed:false},
  {key:'福島県新野地温泉',pref:'福島県',name:'新野地温泉',region:'🍎 東北',stars:2,starStr:'⭐⭐',dayBath:'相模屋旅館',milky:true,mixed:false},
  {key:'福島県幕川温泉',pref:'福島県',name:'幕川温泉',region:'🍎 東北',stars:2,starStr:'⭐⭐',dayBath:'水戸屋旅館、吉倉屋旅館',milky:true,mixed:false},
  {key:'福島県中ノ沢温泉',pref:'福島県',name:'中ノ沢温泉',region:'🍎 東北',stars:2,starStr:'⭐⭐',dayBath:'花見月、蔦屋',milky:true,mixed:false},
  {key:'福島県沼尻温泉',pref:'福島県',name:'沼尻温泉',region:'🍎 東北',stars:2,starStr:'⭐⭐',dayBath:'沼尻温泉ロッジ',milky:true,mixed:false},
  // ===== 🌸 関東 =====
  {key:'群馬県草津温泉',pref:'群馬県',name:'草津温泉',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'大滝乃湯、草津温泉ホテルコサイ、湯宿季の庭',milky:false,mixed:false},
  {key:'神奈川県箱根温泉',pref:'神奈川県',name:'箱根温泉',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'箱根小涌園天悠、強羅花壇、富士屋ホテル',milky:false,mixed:false},
  {key:'群馬県伊香保温泉',pref:'群馬県',name:'伊香保温泉',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'伊香保グランドホテル、木暮旅館',milky:false,mixed:false},
  {key:'群馬県万座温泉',pref:'群馬県',name:'万座温泉',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'万座ホテル聚楽、万座プリンスホテル',milky:true,mixed:true},
  {key:'群馬県四万温泉',pref:'群馬県',name:'四万温泉',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'四万たむら、四万やまぐち館、積善館',milky:false,mixed:true},
  {key:'群馬県みなかみ18湯温泉',pref:'群馬県',name:'みなかみ18湯温泉',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'みなかみ町 月夜野温泉郷',milky:false,mixed:false},
  {key:'群馬県宝川温泉',pref:'群馬県',name:'宝川温泉',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'汪泉閣（470畳・湯浴み着混浴）',milky:false,mixed:true},
  {key:'群馬県尻焼温泉',pref:'群馬県',name:'尻焼温泉',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'無料（川そのものが温泉）',milky:false,mixed:true},
  {key:'群馬県老神温泉',pref:'群馬県',name:'老神温泉',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'伍楼閣（正午〜15時）',milky:false,mixed:true},
  {key:'栃木県鬼怒川温泉',pref:'栃木県',name:'鬼怒川温泉',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'鬼怒川温泉ホテル、あさや',milky:false,mixed:false},
  {key:'栃木県日光湯元温泉',pref:'栃木県',name:'日光湯元温泉',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'奥日光高原ホテル',milky:true,mixed:false},
  {key:'栃木県塩原温泉',pref:'栃木県',name:'塩原新湯温泉',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'ホテル塩原、旅館 彩つむぎ',milky:true,mixed:true},
  {key:'栃木県日光温泉',pref:'栃木県',name:'日光温泉',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'奥日光高原ホテル、ホテルニューパレス',milky:false,mixed:false},
  {key:'栃木県那須湯本温泉',pref:'栃木県',name:'那須湯本温泉（鹿の湯）',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'鹿の湯（500円・1380年前開湯）',milky:true,mixed:true},
  {key:'栃木県塩原元湯温泉',pref:'栃木県',name:'塩原元湯温泉',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'大出館',milky:true,mixed:false},
  {key:'栃木県北温泉',pref:'栃木県',name:'北温泉',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'北温泉旅館（600円）',milky:false,mixed:true},
  {key:'埼玉県鬼怒川上流温泉',pref:'埼玉県',name:'鬼怒川上流温泉',region:'🌸 関東',stars:2,starStr:'⭐⭐',dayBath:'ホテル那智の滝',milky:false,mixed:false},
  {key:'千葉県勝浦温泉',pref:'千葉県',name:'勝浦温泉',region:'🌸 関東',stars:1,starStr:'⭐',dayBath:'ホテル勝浦、丸万旅館',milky:false,mixed:false},
  {key:'千葉県鴨川温泉',pref:'千葉県',name:'鴨川温泉',region:'🌸 関東',stars:1,starStr:'⭐',dayBath:'ホテルグランミラージュ',milky:false,mixed:false},
  {key:'茨城県袋田温泉',pref:'茨城県',name:'袋田温泉',region:'🌸 関東',stars:1,starStr:'⭐',dayBath:'袋田温泉 旅館',milky:false,mixed:false},
  {key:'東京都奥多摩温泉',pref:'東京都',name:'奥多摩温泉',region:'🌸 関東',stars:1,starStr:'⭐',dayBath:'宿 やまぼうし',milky:false,mixed:false},
  {key:'東京都式根島温泉',pref:'東京都',name:'式根島温泉',region:'🌸 関東',stars:1,starStr:'⭐',dayBath:'松が下雅湯（無料・海岸野天混浴）',milky:false,mixed:true},
  // ===== ⛰️ 中部 =====
  {key:'岐阜県下呂温泉',pref:'岐阜県',name:'下呂温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'水明館、下呂観光ホテルしょうげつ、小川屋、湯之島館',milky:false,mixed:false},
  {key:'福井県あわら温泉',pref:'福井県',name:'あわら温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'あわら温泉 青雲閣、福朋プラス',milky:false,mixed:false},
  {key:'石川県和倉温泉',pref:'石川県',name:'和倉温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'加賀屋、あえの風、加賀屋別邸松乃碧',milky:false,mixed:false},
  {key:'石川県山代温泉',pref:'石川県',name:'山代温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'葉渡莉、日本の宿のと楽',milky:false,mixed:false},
  {key:'石川県山中温泉',pref:'石川県',name:'山中温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'竜王の館、南信州伊那ロイヤルホテル',milky:false,mixed:false},
  {key:'長野県野沢温泉',pref:'長野県',name:'野沢温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'野沢温泉 やしおん、ホテル志賀',milky:false,mixed:false},
  {key:'長野県昼神温泉',pref:'長野県',name:'昼神温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'竜王の館、南信州伊那ロイヤルホテル',milky:false,mixed:false},
  {key:'長野県上諏訪温泉',pref:'長野県',name:'上諏訪温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'浜の湯、ホテル霧ヶ峰',milky:false,mixed:false},
  {key:'長野県白馬八方温泉',pref:'長野県',name:'白馬八方温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'白馬オーロラビレッジホテル',milky:false,mixed:false},
  {key:'長野県白骨温泉',pref:'長野県',name:'白骨温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'湯元齢泉 白骨、泡の湯（混浴大露天70坪）',milky:true,mixed:true},
  {key:'長野県乗鞍高原温泉',pref:'長野県',name:'乗鞍高原温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'湯けむり館（710円）',milky:true,mixed:false},
  {key:'長野県五色温泉',pref:'長野県',name:'五色温泉（乗鞍）',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'五色温泉旅館',milky:true,mixed:false},
  {key:'長野県七味温泉',pref:'長野県',name:'七味温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'渓山荘、ホテル花屋',milky:true,mixed:true},
  {key:'長野県奥山田温泉',pref:'長野県',name:'奥山田温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'満山荘',milky:true,mixed:false},
  {key:'山梨県富士急温泉',pref:'山梨県',name:'富士急温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'山中温泉 獅子吼、こおろぎ',milky:false,mixed:false},
  {key:'山梨県下部温泉',pref:'山梨県',name:'下部温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'下部温泉郷 湯之奥鉱泉館',milky:false,mixed:false},
  {key:'富山県宇奈月温泉',pref:'富山県',name:'宇奈月温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'宇奈月温泉 延対寺荘',milky:false,mixed:false},
  {key:'岐阜県飛騨高山温泉',pref:'岐阜県',name:'飛騨高山温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'飛騨亭花扇、ホテルアソシア高山リゾート',milky:false,mixed:false},
  {key:'岐阜県奥飛騨温泉郷',pref:'岐阜県',name:'奥飛騨温泉郷',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'奥飛騨ガーデンホテル焼岳、ひらゆの森',milky:true,mixed:false},
  {key:'岐阜県新穂高温泉',pref:'岐阜県',name:'新穂高温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'穂高荘山のホテル、深山荘（500円）',milky:false,mixed:true},
  {key:'新潟県越後湯沢温泉',pref:'新潟県',name:'越後湯沢温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'越後湯沢温泉ホテル国際、雪國',milky:false,mixed:false},
  {key:'新潟県月岡温泉',pref:'新潟県',name:'月岡温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'ホテル泉迎館',milky:false,mixed:false},
  {key:'新潟県赤倉温泉',pref:'新潟県',name:'赤倉温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'ホテルヴィレッジ、華翠苑',milky:false,mixed:false},
  {key:'新潟県瀬波温泉',pref:'新潟県',name:'瀬波温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'ホテル日高、龍言',milky:false,mixed:false},
  {key:'新潟県燕温泉',pref:'新潟県',name:'燕温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'河原の湯（無料・乳白色野天混浴）',milky:true,mixed:true},
  {key:'新潟県蓮華温泉',pref:'新潟県',name:'蓮華温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'蓮華温泉ロッジ（700円）',milky:true,mixed:true},
  {key:'富山県黒部峡谷温泉',pref:'富山県',name:'黒部峡谷温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'黒部峡谷温泉 泊',milky:false,mixed:false},
  {key:'長野県戸倉上山田温泉',pref:'長野県',name:'戸倉上山田温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'ホテル大日本、ホテル国際21',milky:false,mixed:false},
  {key:'長野県岡谷温泉',pref:'長野県',name:'岡谷温泉',region:'⛰️ 中部',stars:1,starStr:'⭐',dayBath:'ホテル岡谷',milky:false,mixed:false},
  {key:'長野県斑尾高原温泉',pref:'長野県',name:'斑尾高原温泉',region:'⛰️ 中部',stars:0,starStr:'',dayBath:'斑尾高原ホテル',milky:false,mixed:false},
  {key:'岐阜県白川郷温泉',pref:'岐阜県',name:'白川郷温泉',region:'⛰️ 中部',stars:0,starStr:'',dayBath:'お宿 かねや、合掌の湯',milky:false,mixed:false},
  {key:'静岡県熱海温泉',pref:'静岡県',name:'熱海温泉',region:'⛰️ 中部',stars:0,starStr:'',dayBath:'熱海後楽園ホテル、古屋旅館',milky:false,mixed:false},
  {key:'静岡県伊東温泉',pref:'静岡県',name:'伊東温泉',region:'⛰️ 中部',stars:0,starStr:'',dayBath:'ホテルきらら、ホテルニューアカオ',milky:false,mixed:false},
  {key:'静岡県浜名湖かんざんじ温泉',pref:'静岡県',name:'浜名湖かんざんじ温泉',region:'⛰️ 中部',stars:0,starStr:'',dayBath:'ホテルウェルシーズン浜名湖',milky:false,mixed:false},
  {key:'長野県木曽路温泉',pref:'長野県',name:'木曽路温泉',region:'⛰️ 中部',stars:0,starStr:'',dayBath:'ホテル木曽路',milky:false,mixed:false},
  {key:'長野県別所温泉',pref:'長野県',name:'別所温泉',region:'⛰️ 中部',stars:0,starStr:'',dayBath:'旅館 中屋、湯宿 上松屋',milky:false,mixed:false},
  {key:'山梨県西山温泉',pref:'山梨県',name:'西山温泉',region:'⛰️ 中部',stars:0,starStr:'',dayBath:'慶雲館',milky:false,mixed:false},
  {key:'愛知県南知多温泉郷',pref:'愛知県',name:'南知多温泉郷',region:'⛰️ 中部',stars:0,starStr:'',dayBath:'ホテル南知多',milky:false,mixed:false},
  // ===== 🦌 近畿 =====
  {key:'兵庫県有馬温泉',pref:'兵庫県',name:'有馬温泉',region:'🦌 近畿',stars:0,starStr:'',dayBath:'有馬温泉 大黒屋、兆楽',milky:false,mixed:false},
  {key:'兵庫県城崎温泉',pref:'兵庫県',name:'城崎温泉',region:'🦌 近畿',stars:0,starStr:'',dayBath:'西村屋本館、西村屋ホテル招月庭',milky:false,mixed:false},
  {key:'兵庫県淡路島東浦温泉',pref:'兵庫県',name:'淡路島東浦温泉',region:'🦌 近畿',stars:0,starStr:'',dayBath:'ウェスティンホテル淡路',milky:false,mixed:false},
  {key:'和歌山県南紀白浜温泉',pref:'和歌山県',name:'南紀白浜温泉',region:'🦌 近畿',stars:0,starStr:'',dayBath:'南紀白浜温泉ロイヤルホテル',milky:false,mixed:false},
  {key:'滋賀県雄琴温泉',pref:'滋賀県',name:'雄琴温泉',region:'🦌 近畿',stars:0,starStr:'',dayBath:'琵琶湖マリオットホテル',milky:false,mixed:false},
  {key:'京都府天橋立温泉',pref:'京都府',name:'天橋立温泉',region:'🦌 近畿',stars:0,starStr:'',dayBath:'宮津温泉 ホテル北都',milky:false,mixed:false},
  {key:'滋賀県奥びわ温泉',pref:'滋賀県',name:'奥びわ温泉',region:'🦌 近畿',stars:0,starStr:'',dayBath:'ホテル湖南',milky:false,mixed:false},
  {key:'大阪府泉南トルマリン温泉',pref:'大阪府',name:'泉南トルマリン温泉',region:'🦌 近畿',stars:0,starStr:'',dayBath:'ゆりの湯',milky:false,mixed:false},
  {key:'京都府丹後温泉',pref:'京都府',name:'丹後温泉',region:'🦌 近畿',stars:0,starStr:'',dayBath:'丹後温泉 琴引浜',milky:false,mixed:false},
  {key:'和歌山県田辺温泉',pref:'和歌山県',name:'田辺温泉',region:'🦌 近畿',stars:0,starStr:'',dayBath:'ホテル季楽、うめ乃湯',milky:false,mixed:false},
  {key:'和歌山県川湯温泉',pref:'和歌山県',name:'川湯温泉（仙人風呂）',region:'🦌 近畿',stars:0,starStr:'',dayBath:'仙人風呂（12〜2月無料・川を堰き止めた超大型混浴）',milky:false,mixed:true},
  {key:'三重県志摩温泉',pref:'三重県',name:'志摩温泉',region:'🦌 近畿',stars:0,starStr:'',dayBath:'志摩観光ホテル',milky:false,mixed:false},
  {key:'奈良県洞川温泉',pref:'奈良県',name:'洞川温泉',region:'🦌 近畿',stars:0,starStr:'',dayBath:'旅館 渓山、旅館 杉の湯',milky:false,mixed:false},
  // ===== ⛩️ 中国・四国 =====
  {key:'愛媛県道後温泉',pref:'愛媛県',name:'道後温泉',region:'⛩️ 中国・四国',stars:0,starStr:'',dayBath:'道後舘、花ゆづき、別邸朧月夜、ホテル椿館',milky:false,mixed:false},
  {key:'香川県こんぴら温泉郷',pref:'香川県',name:'こんぴら温泉郷',region:'⛩️ 中国・四国',stars:0,starStr:'',dayBath:'琴参閣、こんぴら温泉華の湯',milky:false,mixed:false},
  {key:'山口県長門湯本温泉',pref:'山口県',name:'長門湯本温泉',region:'⛩️ 中国・四国',stars:0,starStr:'',dayBath:'長門天然温泉',milky:false,mixed:false},
  {key:'広島県宮島温泉',pref:'広島県',name:'宮島温泉',region:'⛩️ 中国・四国',stars:0,starStr:'',dayBath:'グランドホテル有もと、星の宿',milky:false,mixed:false},
  {key:'香川県高松温泉',pref:'香川県',name:'高松温泉',region:'⛩️ 中国・四国',stars:0,starStr:'',dayBath:'スパイラル高松',milky:false,mixed:false},
  {key:'徳島県祖谷温泉',pref:'徳島県',name:'祖谷温泉',region:'⛩️ 中国・四国',stars:0,starStr:'',dayBath:'ホテル祖谷温泉',milky:false,mixed:false},
  {key:'愛媛県北条温泉',pref:'愛媛県',name:'北条温泉',region:'⛩️ 中国・四国',stars:0,starStr:'',dayBath:'ホテルしおさい北条',milky:false,mixed:false},
  {key:'山口県湯田温泉',pref:'山口県',name:'湯田温泉',region:'⛩️ 中国・四国',stars:0,starStr:'',dayBath:'ホテル湯田、山陽旅館',milky:false,mixed:false},
  {key:'鳥取県三朝温泉',pref:'鳥取県',name:'三朝温泉',region:'⛩️ 中国・四国',stars:0,starStr:'',dayBath:'ホテル泉都、旅館 大橋',milky:false,mixed:false},
  {key:'島根県玉造温泉',pref:'島根県',name:'玉造温泉',region:'⛩️ 中国・四国',stars:0,starStr:'',dayBath:'佳翠苑皆美、ホテル玉泉',milky:false,mixed:false},
  {key:'岡山県湯郷温泉',pref:'岡山県',name:'湯郷温泉',region:'⛩️ 中国・四国',stars:0,starStr:'',dayBath:'ホテル東亜、旅館 ひらたや',milky:false,mixed:false},
  {key:'高知県いの町温泉',pref:'高知県',name:'いの町温泉',region:'⛩️ 中国・四国',stars:0,starStr:'',dayBath:'いの町温泉 旅館',milky:false,mixed:false},
  // ===== 🌺 九州・沖縄 =====
  {key:'大分県別府八湯温泉',pref:'大分県',name:'別府八湯温泉',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'杉乃井ホテル、別府温泉ホテル、竹瓦温泉',milky:true,mixed:false},
  {key:'鹿児島県指宿温泉',pref:'鹿児島県',name:'指宿温泉',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'いぶすき秀水園、指宿白水館',milky:false,mixed:false},
  {key:'熊本県黒川温泉',pref:'熊本県',name:'黒川温泉',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'黒川荘、山みず木、旅館山河',milky:false,mixed:true},
  {key:'大分県由布院温泉',pref:'大分県',name:'由布院温泉',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'亀の井別荘、由布院玉の湯',milky:false,mixed:false},
  {key:'福岡県福岡温泉',pref:'福岡県',name:'福岡温泉',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'博多の湯',milky:false,mixed:false},
  {key:'大分県奥日田温泉',pref:'大分県',name:'奥日田温泉',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'旅館 中山館',milky:false,mixed:false},
  {key:'福岡県二日市温泉',pref:'福岡県',name:'二日市温泉',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'太宰府温泉',milky:false,mixed:false},
  {key:'佐賀県嬉野温泉',pref:'佐賀県',name:'嬉野温泉',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'ホテル桜、旅館 大村屋',milky:false,mixed:false},
  {key:'長崎県小浜温泉',pref:'長崎県',name:'小浜温泉',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'ホテル小浜、しおさい小浜',milky:false,mixed:false},
  {key:'熊本県菊池温泉',pref:'熊本県',name:'菊池温泉',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'ホテルパレス',milky:false,mixed:false},
  {key:'熊本県玉名温泉',pref:'熊本県',name:'玉名温泉',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'ホテルメイ',milky:false,mixed:false},
  {key:'福岡県原鶴温泉',pref:'福岡県',name:'原鶴温泉',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'ホテル原鶴',milky:false,mixed:false},
  {key:'熊本県豊礼の湯',pref:'熊本県',name:'豊礼の湯',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'豊礼の湯（500円・コバルトブルー乳白色）',milky:true,mixed:true},
  {key:'熊本県赤川温泉',pref:'熊本県',name:'赤川温泉',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'赤川荘（300円）',milky:true,mixed:false},
  {key:'長崎県雲仙温泉',pref:'長崎県',name:'雲仙温泉',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'小地獄温泉館（300円）',milky:true,mixed:false},
  {key:'宮崎県霧島温泉郷',pref:'宮崎県',name:'霧島温泉郷',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'霧島ホテル',milky:false,mixed:false},
  {key:'鹿児島県霧島新湯温泉',pref:'鹿児島県',name:'霧島新湯温泉',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'湯之谷山荘（500円・乳白色硫黄泉）',milky:true,mixed:false},
  {key:'沖縄県那覇温泉',pref:'沖縄県',name:'那覇温泉',region:'🌺 九州・沖縄',stars:0,starStr:'',dayBath:'那覇温泉 ホテル那覇',milky:false,mixed:false},
  // ===== 🔥 全国秘湯・野湯 67選 =====
  {key:'秘湯_01_養老牛温泉',pref:'北海道',name:'養老牛温泉 からまつの湯',region:'🌨️ 北海道',stars:3,starStr:'',dayBath:'からまつの湯（野湯・無料）',milky:false,mixed:true},
  {key:'秘湯_02_コタン温泉',pref:'北海道',name:'コタン温泉 露天風呂',region:'🌨️ 北海道',stars:3,starStr:'',dayBath:'コタン温泉（無料）',milky:false,mixed:true},
  {key:'秘湯_03_水無海浜温泉',pref:'北海道',name:'水無海浜温泉',region:'🌨️ 北海道',stars:2,starStr:'',dayBath:'水無海浜温泉（無料・海岸野天）',milky:false,mixed:true},
  {key:'秘湯_04_然別峡かんの温泉',pref:'北海道',name:'然別峡 かんの温泉',region:'🌨️ 北海道',stars:1,starStr:'',dayBath:'かんの温泉',milky:false,mixed:false},
  {key:'秘湯_05_屈斜路湖砂湯',pref:'北海道',name:'屈斜路湖 砂湯',region:'🌨️ 北海道',stars:1,starStr:'',dayBath:'砂湯（無料・砂を掘ると湯が出る）',milky:false,mixed:false},
  {key:'秘湯_06_岩尾別温泉',pref:'北海道',name:'岩尾別温泉 三段の湯',region:'🌨️ 北海道',stars:1,starStr:'',dayBath:'三段の湯（無料）',milky:false,mixed:true},
  {key:'秘湯_07_酸ヶ湯薬師の湯',pref:'青森県',name:'酸ヶ湯温泉 薬師の湯',region:'🍎 東北',stars:3,starStr:'',dayBath:'酸ヶ湯温泉旅館（600円）',milky:true,mixed:false},
  {key:'秘湯_08_恐山宿坊の湯',pref:'青森県',name:'恐山温泉 宿坊の湯',region:'🍎 東北',stars:2,starStr:'',dayBath:'恐山菩提寺（500円）',milky:false,mixed:false},
  {key:'秘湯_09_不老ふ死温泉',pref:'青森県',name:'不老ふ死温泉',region:'🍎 東北',stars:1,starStr:'',dayBath:'不老ふ死温泉（600円・海辺の混浴）',milky:false,mixed:true},
  {key:'秘湯_10_黄金崎不老ふ死温泉',pref:'青森県',name:'黄金崎不老ふ死温泉',region:'🍎 東北',stars:1,starStr:'',dayBath:'黄金崎不老ふ死温泉（600円）',milky:false,mixed:true},
  {key:'秘湯_11_藤七温泉彩雲荘',pref:'岩手県',name:'藤七温泉 彩雲荘',region:'🍎 東北',stars:2,starStr:'',dayBath:'彩雲荘（東北最高所・泥パック混浴）',milky:true,mixed:true},
  {key:'秘湯_12_松川温泉峡雲荘',pref:'岩手県',name:'松川温泉 峡雲荘',region:'🍎 東北',stars:1,starStr:'',dayBath:'峡雲荘、松楓荘',milky:true,mixed:false},
  {key:'秘湯_13_川原毛大滝湯',pref:'秋田県',name:'川原毛大滝湯',region:'🍎 東北',stars:3,starStr:'',dayBath:'川原毛大滝湯（無料・秘境滝壺混浴）',milky:false,mixed:true},
  {key:'秘湯_14_泥湯温泉奥湯沢',pref:'秋田県',name:'泥湯温泉 奥湯沢',region:'🍎 東北',stars:2,starStr:'',dayBath:'奥山旅館',milky:false,mixed:false},
  {key:'秘湯_15_蒸ノ湯温泉',pref:'秋田県',name:'蒸ノ湯温泉',region:'🍎 東北',stars:1,starStr:'',dayBath:'ふけの湯温泉（700円）',milky:true,mixed:true},
  {key:'秘湯_16_乳頭温泉鶴の湯',pref:'秋田県',name:'乳頭温泉郷 鶴の湯',region:'🍎 東北',stars:1,starStr:'',dayBath:'鶴の湯（600円）',milky:true,mixed:true},
  {key:'秘湯_17_姥湯温泉桝形屋',pref:'山形県',name:'姥湯温泉 桝形屋',region:'🍎 東北',stars:2,starStr:'',dayBath:'枡形屋（要予約）',milky:true,mixed:true},
  {key:'秘湯_18_滑川温泉福島屋',pref:'山形県',name:'滑川温泉 福島屋',region:'🍎 東北',stars:1,starStr:'',dayBath:'滑川温泉 福島屋',milky:true,mixed:false},
  {key:'秘湯_19_湯の平温泉',pref:'福島県',name:'湯の平温泉',region:'🍎 東北',stars:3,starStr:'',dayBath:'湯の平温泉（秘境・要登山）',milky:false,mixed:false},
  {key:'秘湯_20_湯ノ花温泉石湯',pref:'福島県',name:'湯ノ花温泉 石湯',region:'🍎 東北',stars:2,starStr:'',dayBath:'石湯（200円・混浴共同浴場）',milky:false,mixed:true},
  {key:'秘湯_21_木賊温泉岩風呂',pref:'福島県',name:'木賊温泉 岩風呂',region:'🍎 東北',stars:1,starStr:'',dayBath:'岩風呂（無料・川沿い混浴）',milky:false,mixed:true},
  {key:'秘湯_22_那須三斗小屋温泉',pref:'栃木県',name:'那須 三斗小屋温泉',region:'🌸 関東',stars:1,starStr:'',dayBath:'煙草屋旅館、大黒屋旅館（登山者向け）',milky:false,mixed:true},
  {key:'秘湯_23_北温泉旅館',pref:'栃木県',name:'北温泉 旅館',region:'🌸 関東',stars:2,starStr:'',dayBath:'北温泉旅館（600円）',milky:false,mixed:true},
  {key:'秘湯_24_手白澤温泉',pref:'栃木県',name:'奥鬼怒温泉郷 手白澤温泉',region:'🌸 関東',stars:2,starStr:'',dayBath:'手白澤温泉（宿泊のみ）',milky:false,mixed:false},
  {key:'秘湯_25_尻焼温泉',pref:'群馬県',name:'尻焼温泉',region:'🌸 関東',stars:3,starStr:'',dayBath:'無料（川そのものが温泉）',milky:false,mixed:true},
  {key:'秘湯_26_法師温泉長寿館',pref:'群馬県',name:'法師温泉 長寿館',region:'🌸 関東',stars:3,starStr:'',dayBath:'長寿館（600円・重要文化財の混浴）',milky:false,mixed:true},
  {key:'秘湯_27_湯宿だいこく屋',pref:'群馬県',name:'湯宿だいこく屋',region:'🌸 関東',stars:3,starStr:'',dayBath:'だいこく屋',milky:false,mixed:true},
  {key:'秘湯_28_万座温泉空吹',pref:'群馬県',name:'万座温泉 空吹',region:'🌸 関東',stars:1,starStr:'',dayBath:'万座プリンスホテル等',milky:true,mixed:false},
  {key:'秘湯_29_蓮華温泉',pref:'新潟県',name:'蓮華温泉',region:'⛰️ 中部',stars:3,starStr:'',dayBath:'蓮華温泉ロッジ（700円）',milky:false,mixed:true},
  {key:'秘湯_30_赤湯温泉山口館',pref:'新潟県',name:'赤湯温泉 山口館',region:'⛰️ 中部',stars:1,starStr:'',dayBath:'山口館（登山者向け秘湯）',milky:false,mixed:true},
  {key:'秘湯_31_地獄谷野天風呂',pref:'長野県',name:'地獄谷野天風呂',region:'⛰️ 中部',stars:3,starStr:'',dayBath:'後楽館（500円・猿と入浴で有名）',milky:false,mixed:true},
  {key:'秘湯_32_切明温泉川の湯',pref:'長野県',name:'切明温泉 川の湯',region:'⛰️ 中部',stars:3,starStr:'',dayBath:'無料（川の中に湧く野天）',milky:false,mixed:true},
  {key:'秘湯_33_加賀井温泉一陽館',pref:'長野県',name:'加賀井温泉 一陽館',region:'⛰️ 中部',stars:2,starStr:'',dayBath:'一陽館（300円・茶褐色の名湯）',milky:false,mixed:false},
  {key:'秘湯_34_高峰温泉',pref:'長野県',name:'高峰温泉',region:'⛰️ 中部',stars:1,starStr:'',dayBath:'高峰温泉（ランプの宿）',milky:true,mixed:true},
  {key:'秘湯_35_中房温泉',pref:'長野県',name:'中房温泉',region:'⛰️ 中部',stars:1,starStr:'',dayBath:'中房温泉',milky:false,mixed:false},
  {key:'秘湯_36_ガマの湯黒部峡谷',pref:'富山県',name:'ガマの湯（黒部峡谷）',region:'⛰️ 中部',stars:3,starStr:'',dayBath:'黒部峡谷 祖母谷温泉周辺（要登山）',milky:false,mixed:true},
  {key:'秘湯_37_みくりが池温泉',pref:'富山県',name:'みくりが池温泉',region:'⛰️ 中部',stars:1,starStr:'',dayBath:'みくりが池温泉（日本最高所の温泉宿）',milky:true,mixed:false},
  {key:'秘湯_38_新穂高の湯',pref:'岐阜県',name:'奥飛騨温泉郷 新穂高の湯',region:'⛰️ 中部',stars:2,starStr:'',dayBath:'新穂高の湯（無料・川沿い混浴）',milky:false,mixed:true},
  {key:'秘湯_39_白骨温泉噴湯丘',pref:'長野県',name:'白骨温泉 噴湯丘',region:'⛰️ 中部',stars:2,starStr:'',dayBath:'泡の湯（混浴大露天）',milky:true,mixed:false},
  {key:'秘湯_40_寸又峡温泉',pref:'静岡県',name:'寸又峡温泉',region:'⛰️ 中部',stars:2,starStr:'',dayBath:'翠紅苑、クレスト',milky:false,mixed:false},
  {key:'秘湯_41_十津川温泉庵の湯',pref:'奈良県',name:'十津川温泉 庵の湯',region:'🦌 近畿',stars:3,starStr:'',dayBath:'庵の湯（450円・日本一の露天）',milky:false,mixed:false},
  {key:'秘湯_42_仙人風呂',pref:'和歌山県',name:'仙人風呂',region:'🦌 近畿',stars:3,starStr:'',dayBath:'仙人風呂（12〜2月無料・超大型混浴）',milky:false,mixed:true},
  {key:'秘湯_43_湯の峰温泉つぼ湯',pref:'和歌山県',name:'湯の峰温泉 つぼ湯',region:'🦌 近畿',stars:3,starStr:'',dayBath:'つぼ湯（770円・世界遺産の温泉）',milky:false,mixed:true},
  {key:'秘湯_44_川湯温泉露天風呂',pref:'和歌山県',name:'川湯温泉 露天風呂',region:'🦌 近畿',stars:1,starStr:'',dayBath:'川湯温泉（無料・川の中）',milky:false,mixed:true},
  {key:'秘湯_45_三朝温泉河原風呂',pref:'鳥取県',name:'三朝温泉 河原風呂',region:'⛩️ 中国・四国',stars:2,starStr:'',dayBath:'河原風呂（無料・混浴）',milky:false,mixed:true},
  {key:'秘湯_46_奥津温泉洗濯場',pref:'岡山県',name:'奥津温泉 洗濯場',region:'⛩️ 中国・四国',stars:2,starStr:'',dayBath:'奥津温泉（無料・洗濯もできる足湯）',milky:false,mixed:true},
  {key:'秘湯_47_湯原温泉砂湯',pref:'岡山県',name:'湯原温泉 砂湯',region:'⛩️ 中国・四国',stars:2,starStr:'',dayBath:'砂湯（無料・日本三大露天）',milky:false,mixed:true},
  {key:'秘湯_48_真賀温泉幕湯',pref:'岡山県',name:'真賀温泉 幕湯',region:'⛩️ 中国・四国',stars:1,starStr:'',dayBath:'幕湯（200円・洞窟混浴）',milky:false,mixed:true},
  {key:'秘湯_49_祖谷温泉',pref:'徳島県',name:'祖谷温泉',region:'⛩️ 中国・四国',stars:2,starStr:'',dayBath:'ホテル祖谷温泉（ケーブルカーで降りる露天）',milky:false,mixed:false},
  {key:'秘湯_50_道後温泉椿の湯',pref:'愛媛県',name:'道後温泉 椿の湯',region:'⛩️ 中国・四国',stars:1,starStr:'',dayBath:'椿の湯（460円）',milky:false,mixed:false},
  {key:'秘湯_51_別府鍋山の湯',pref:'大分県',name:'別府温泉 鍋山の湯',region:'🌺 九州・沖縄',stars:2,starStr:'',dayBath:'鍋山の湯（無料・泥湯混浴）',milky:false,mixed:true},
  {key:'秘湯_52_別府鶴の湯',pref:'大分県',name:'別府温泉 鶴の湯',region:'🌺 九州・沖縄',stars:1,starStr:'',dayBath:'鶴の湯（無料）',milky:false,mixed:true},
  {key:'秘湯_53_別府へびん湯',pref:'大分県',name:'別府温泉 へびん湯',region:'🌺 九州・沖縄',stars:1,starStr:'',dayBath:'へびん湯（無料）',milky:false,mixed:true},
  {key:'秘湯_54_塚原温泉火口乃泉',pref:'大分県',name:'塚原温泉 火口乃泉',region:'🌺 九州・沖縄',stars:1,starStr:'',dayBath:'火口乃泉（600円・強酸性白濁）',milky:true,mixed:false},
  {key:'秘湯_55_長湯温泉ガニ湯',pref:'大分県',name:'長湯温泉 ガニ湯',region:'🌺 九州・沖縄',stars:1,starStr:'',dayBath:'ガニ湯（無料・川の中の露天）',milky:false,mixed:true},
  {key:'秘湯_56_満願寺温泉川風呂',pref:'熊本県',name:'満願寺温泉 川風呂',region:'🌺 九州・沖縄',stars:3,starStr:'',dayBath:'川風呂（無料・日本一の混浴）',milky:false,mixed:true},
  {key:'秘湯_57_地獄温泉青風荘',pref:'熊本県',name:'地獄温泉 青風荘',region:'🌺 九州・沖縄',stars:2,starStr:'',dayBath:'青風荘（日帰り可・乳白色）',milky:true,mixed:true},
  {key:'秘湯_58_弓ヶ浜温泉湯楽亭',pref:'熊本県',name:'弓ヶ浜温泉 湯楽亭',region:'🌺 九州・沖縄',stars:1,starStr:'',dayBath:'湯楽亭',milky:false,mixed:false},
  {key:'秘湯_59_妙見温泉泥の湯',pref:'鹿児島県',name:'妙見温泉 泥の湯',region:'🌺 九州・沖縄',stars:1,starStr:'',dayBath:'秀水湯（泥湯混浴）',milky:false,mixed:true},
  {key:'秘湯_60_霧島最古の岩風呂',pref:'鹿児島県',name:'霧島最古の岩風呂',region:'🌺 九州・沖縄',stars:1,starStr:'',dayBath:'霧島湯之谷山荘',milky:false,mixed:true},
  {key:'秘湯_61_指宿砂むし会館',pref:'鹿児島県',name:'指宿温泉 砂むし会館',region:'🌺 九州・沖縄',stars:3,starStr:'',dayBath:'砂むし会館 砂楽（1,100円）',milky:false,mixed:false},
  {key:'秘湯_62_硫黄島東温泉',pref:'鹿児島県',name:'硫黄島 東温泉',region:'🌺 九州・沖縄',stars:2,starStr:'',dayBath:'東温泉（無料・海辺の秘湯）',milky:false,mixed:true},
  {key:'秘湯_63_平内海中温泉',pref:'鹿児島県',name:'平内海中温泉',region:'🌺 九州・沖縄',stars:2,starStr:'',dayBath:'平内海中温泉（無料・干潮時のみ入浴可）',milky:false,mixed:true},
  {key:'秘湯_64_湯向温泉',pref:'鹿児島県',name:'湯向温泉',region:'🌺 九州・沖縄',stars:1,starStr:'',dayBath:'湯向温泉',milky:true,mixed:false},
  {key:'秘湯_65_小浜温泉茜',pref:'長崎県',name:'小浜温泉 茜',region:'🌺 九州・沖縄',stars:1,starStr:'',dayBath:'茜（600円）',milky:false,mixed:false},
  {key:'秘湯_66_古湯温泉おんくり',pref:'佐賀県',name:'古湯温泉 おんくり',region:'🌺 九州・沖縄',stars:1,starStr:'',dayBath:'おんくり（250円）',milky:false,mixed:false},
  {key:'秘湯_67_玉名温泉立願屋',pref:'熊本県',name:'玉名温泉 立願屋',region:'🌺 九州・沖縄',stars:1,starStr:'',dayBath:'立願屋',milky:false,mixed:false},

];

const ONSEN_COORDS = {
  '北海道登別温泉':[141.10,42.43],'北海道湯の川温泉':[141.68,41.78],
  '北海道定山渓温泉':[141.10,42.98],'北海道ニセコ温泉':[140.69,42.80],
  '北海道網走温泉':[144.27,43.97],'北海道美幌峠温泉':[144.07,43.83],
  '北海道阿寒湖温泉':[144.10,43.45],'北海道屈斜路温泉':[144.35,43.60],
  '北海道羅臼温泉':[145.20,44.02],
  '青森県酸ヶ湯温泉':[140.88,40.65],'青森県浅虫温泉':[140.87,40.85],
  '青森県大鰐温泉':[140.57,40.52],
  '青森県谷地温泉':[140.77,40.55],'青森県八甲田温泉':[140.88,40.67],
  '青森県嶽温泉':[140.52,40.67],'青森県下風呂温泉':[141.12,41.45],
  '青森県恐山温泉':[141.22,41.32],
  '岩手県繫温泉':[140.90,39.72],'岩手県花巻温泉郷':[141.12,39.37],
  '岩手県金田一温泉':[141.28,40.31],'岩手県つなぎ温泉':[141.05,39.68],
  '岩手県藤七温泉':[140.97,39.95],'岩手県松川温泉':[141.00,39.93],
  '岩手県須川温泉':[140.82,39.02],'岩手県大沢温泉':[141.12,39.37],
  '宮城県鳴子温泉':[140.73,38.73],'宮城県松島温泉':[141.07,38.37],
  '宮城県作並温泉':[140.63,38.33],
  '秋田県玉川温泉':[140.73,39.95],
  '秋田県乳頭温泉郷':[140.75,39.77],'秋田県後生掛温泉':[140.77,39.97],
  '秋田県蒸の湯温泉':[140.75,39.97],'秋田県泥湯温泉':[140.65,39.47],
  '山形県蔵王温泉':[140.45,38.17],'山形県肘折温泉':[140.27,38.72],
  '山形県天童温泉':[140.38,38.35],
  '山形県姥湯温泉':[140.22,37.90],'山形県滑川温泉':[140.18,37.92],
  '福島県磐梯熱海温泉':[140.15,37.47],'福島県土湯温泉':[140.28,37.65],
  '福島県会津東山温泉':[139.93,37.50],'福島県飯坂温泉':[140.35,37.77],
  '福島県いわき湯本温泉':[140.93,36.98],
  '福島県高湯温泉':[140.28,37.68],'福島県野地温泉':[140.22,37.72],
  '福島県新野地温泉':[140.23,37.73],'福島県幕川温泉':[140.17,37.73],
  '福島県中ノ沢温泉':[140.12,37.58],'福島県沼尻温泉':[140.15,37.60],
  '群馬県草津温泉':[138.60,36.62],'神奈川県箱根温泉':[139.02,35.23],
  '群馬県伊香保温泉':[138.88,36.47],'群馬県万座温泉':[138.47,36.57],
  '群馬県四万温泉':[138.82,36.68],'群馬県みなかみ18湯温泉':[138.97,36.77],
  '群馬県宝川温泉':[139.05,36.85],'群馬県尻焼温泉':[138.57,36.67],
  '群馬県老神温泉':[139.28,36.72],
  '栃木県鬼怒川温泉':[139.60,36.83],'栃木県日光湯元温泉':[139.40,36.80],
  '栃木県塩原温泉':[139.83,36.97],'栃木県日光温泉':[139.62,36.75],
  '栃木県那須湯本温泉':[139.97,37.10],'栃木県塩原元湯温泉':[139.82,36.98],
  '栃木県北温泉':[139.95,37.10],
  '埼玉県鬼怒川上流温泉':[139.60,36.87],'千葉県勝浦温泉':[140.13,35.15],
  '千葉県鴨川温泉':[140.10,35.10],'茨城県袋田温泉':[140.38,36.77],
  '東京都奥多摩温泉':[139.10,35.78],'東京都式根島温泉':[139.22,34.33],
  '岐阜県下呂温泉':[137.25,35.80],'福井県あわら温泉':[136.23,36.23],
  '石川県和倉温泉':[136.98,37.05],'石川県山代温泉':[136.45,36.37],
  '石川県山中温泉':[136.38,36.27],
  '長野県野沢温泉':[138.43,36.92],'長野県昼神温泉':[137.67,35.47],
  '長野県上諏訪温泉':[138.12,36.03],'長野県白馬八方温泉':[137.87,36.70],
  '長野県白骨温泉':[137.72,36.17],
  '長野県乗鞍高原温泉':[137.62,36.13],'長野県五色温泉':[137.60,36.10],
  '長野県七味温泉':[138.35,36.52],'長野県奥山田温泉':[138.37,36.53],
  '山梨県富士急温泉':[138.57,35.37],'山梨県下部温泉':[138.47,35.47],
  '富山県宇奈月温泉':[137.58,36.87],'岐阜県飛騨高山温泉':[137.25,36.15],
  '岐阜県奥飛騨温泉郷':[137.58,36.42],'岐阜県新穂高温泉':[137.58,36.43],
  '新潟県越後湯沢温泉':[138.82,36.93],'新潟県月岡温泉':[139.28,37.77],
  '新潟県赤倉温泉':[138.55,36.95],'新潟県瀬波温泉':[139.42,38.08],
  '新潟県燕温泉':[138.73,36.92],'新潟県蓮華温泉':[137.88,36.77],
  '富山県黒部峡谷温泉':[137.65,36.88],
  '長野県戸倉上山田温泉':[138.18,36.42],'長野県岡谷温泉':[138.05,36.07],
  '長野県斑尾高原温泉':[138.37,36.93],'長野県木曽路温泉':[137.72,35.87],
  '長野県別所温泉':[138.15,36.35],'山梨県西山温泉':[138.27,35.57],
  '愛知県南知多温泉郷':[136.93,34.70],
  '兵庫県有馬温泉':[135.25,34.80],'兵庫県城崎温泉':[134.82,35.63],
  '兵庫県淡路島東浦温泉':[134.97,34.47],'和歌山県南紀白浜温泉':[135.37,33.68],
  '滋賀県雄琴温泉':[135.88,35.12],'京都府天橋立温泉':[135.18,35.57],
  '滋賀県奥びわ温泉':[136.12,35.53],'大阪府泉南トルマリン温泉':[135.37,34.37],
  '京都府丹後温泉':[135.07,35.62],'和歌山県田辺温泉':[135.37,33.73],
  '和歌山県川湯温泉':[135.92,33.87],
  '三重県志摩温泉':[136.83,34.32],'奈良県洞川温泉':[135.92,34.22],
  '愛媛県道後温泉':[132.88,33.85],'香川県こんぴら温泉郷':[133.82,34.18],
  '山口県長門湯本温泉':[131.42,34.38],'広島県宮島温泉':[132.32,34.30],
  '香川県高松温泉':[134.05,34.35],'徳島県祖谷温泉':[133.88,33.90],
  '愛媛県北条温泉':[132.73,33.97],'山口県湯田温泉':[131.47,34.17],
  '鳥取県三朝温泉':[133.83,35.37],'島根県玉造温泉':[132.97,35.43],
  '岡山県湯郷温泉':[134.18,34.98],'高知県いの町温泉':[133.42,33.55],
  '大分県別府八湯温泉':[131.48,33.28],'鹿児島県指宿温泉':[130.63,31.25],
  '熊本県黒川温泉':[131.08,33.00],'大分県由布院温泉':[131.37,33.25],
  '福岡県福岡温泉':[130.42,33.60],'大分県奥日田温泉':[131.12,33.33],
  '福岡県二日市温泉':[130.52,33.52],'佐賀県嬉野温泉':[130.00,33.10],
  '長崎県小浜温泉':[130.20,32.72],'熊本県菊池温泉':[130.82,32.98],
  '熊本県玉名温泉':[130.57,32.92],'福岡県原鶴温泉':[130.72,33.38],
  '熊本県豊礼の湯':[131.18,33.22],'熊本県赤川温泉':[131.23,33.12],
  '長崎県雲仙温泉':[130.22,32.72],
  '宮崎県霧島温泉郷':[130.87,31.90],'鹿児島県霧島新湯温泉':[130.88,31.92],
  '鹿児島県指宿温泉':[130.63,31.25],'沖縄県那覇温泉':[127.68,26.22],
  '秘湯_01_養老牛温泉':[144.757,43.6063],
  '秘湯_02_コタン温泉':[144.3312,43.5701],
  '秘湯_03_水無海浜温泉':[141.1685,41.8152],
  '秘湯_04_然別峡かんの温泉':[143.0458,43.3762],
  '秘湯_05_屈斜路湖砂湯':[144.3752,43.6190],
  '秘湯_06_岩尾別温泉':[145.0839,44.1370],
  '秘湯_07_酸ヶ湯薬師の湯':[140.8488,40.6473],
  '秘湯_08_恐山宿坊の湯':[141.0911,41.3283],
  '秘湯_09_不老ふ死温泉':[139.9022,40.5891],
  '秘湯_10_黄金崎不老ふ死温泉':[139.9015,40.5895],
  '秘湯_11_藤七温泉彩雲荘':[140.8504,39.9491],
  '秘湯_12_松川温泉峡雲荘':[140.9194,39.8751],
  '秘湯_13_川原毛大滝湯':[140.5401,39.0232],
  '秘湯_14_泥湯温泉奥湯沢':[140.5639,38.9953],
  '秘湯_15_蒸ノ湯温泉':[140.8406,39.9678],
  '秘湯_16_乳頭温泉鶴の湯':[140.7844,39.8105],
  '秘湯_17_姥湯温泉桝形屋':[140.1601,37.7554],
  '秘湯_18_滑川温泉福島屋':[140.1764,37.7719],
  '秘湯_19_湯の平温泉':[139.5594,37.8184],
  '秘湯_20_湯ノ花温泉石湯':[139.5303,37.0782],
  '秘湯_21_木賊温泉岩風呂':[139.4795,37.0601],
  '秘湯_22_那須三斗小屋温泉':[139.9231,37.1408],
  '秘湯_23_北温泉旅館':[139.9912,37.1265],
  '秘湯_24_手白澤温泉':[139.4092,36.8831],
  '秘湯_25_尻焼温泉':[138.6548,36.6385],
  '秘湯_26_法師温泉長寿館':[138.8344,36.7214],
  '秘湯_27_湯宿だいこく屋':[138.8576,36.6908],
  '秘湯_28_万座温泉空吹':[138.5089,36.6433],
  '秘湯_29_蓮華温泉':[137.7818,36.8858],
  '秘湯_30_赤湯温泉山口館':[138.7490,36.7645],
  '秘湯_31_地獄谷野天風呂':[138.4623,36.7329],
  '秘湯_32_切明温泉川の湯':[138.6019,36.7844],
  '秘湯_33_加賀井温泉一陽館':[138.1889,36.5501],
  '秘湯_34_高峰温泉':[138.4697,36.4172],
  '秘湯_35_中房温泉':[137.7475,36.3922],
  '秘湯_36_ガマの湯黒部峡谷':[137.6744,36.6917],
  '秘湯_37_みくりが池温泉':[137.6006,36.5772],
  '秘湯_38_新穂高の湯':[137.5753,36.2847],
  '秘湯_39_白骨温泉噴湯丘':[137.6256,36.1472],
  '秘湯_40_寸又峡温泉':[138.1158,35.1831],
  '秘湯_41_十津川温泉庵の湯':[135.7761,33.9161],
  '秘湯_42_仙人風呂':[135.7578,33.8294],
  '秘湯_43_湯の峰温泉つぼ湯':[135.7583,33.8281],
  '秘湯_44_川湯温泉露天風呂':[135.7591,33.8291],
  '秘湯_45_三朝温泉河原風呂':[133.8944,35.4111],
  '秘湯_46_奥津温泉洗濯場':[133.9142,35.2289],
  '秘湯_47_湯原温泉砂湯':[133.7386,35.1764],
  '秘湯_48_真賀温泉幕湯':[133.7297,35.1436],
  '秘湯_49_祖谷温泉':[133.8239,33.9156],
  '秘湯_50_道後温泉椿の湯':[132.7856,33.8491],
  '秘湯_51_別府鍋山の湯':[131.4328,33.3150],
  '秘湯_52_別府鶴の湯':[131.4394,33.3125],
  '秘湯_53_別府へびん湯':[131.4308,33.3164],
  '秘湯_54_塚原温泉火口乃泉':[131.4589,33.3197],
  '秘湯_55_長湯温泉ガニ湯':[131.3789,33.1011],
  '秘湯_56_満願寺温泉川風呂':[131.0961,33.0801],
  '秘湯_57_地獄温泉青風荘':[131.0475,32.8856],
  '秘湯_58_弓ヶ浜温泉湯楽亭':[130.4358,32.5594],
  '秘湯_59_妙見温泉泥の湯':[130.7553,31.8489],
  '秘湯_60_霧島最古の岩風呂':[130.7600,31.8483],
  '秘湯_61_指宿砂むし会館':[130.6489,31.2333],
  '秘湯_62_硫黄島東温泉':[130.3161,30.7931],
  '秘湯_63_平内海中温泉':[130.5058,30.2289],
  '秘湯_64_湯向温泉':[130.2178,30.4681],
  '秘湯_65_小浜温泉茜':[130.2014,32.7303],
  '秘湯_66_古湯温泉おんくり':[130.2244,33.3761],
  '秘湯_67_玉名温泉立願屋':[130.5611,32.9328],

};

const GOURMET_DATA = [
  {key:"北海道ジンギスカン",pref:"北海道",city:"札幌市",food:"ジンギスカン",shop:"成吉思汗 だるま",coords:[141.35,43.06]},
  {key:"北海道スープカレー",pref:"北海道",city:"札幌市",food:"スープカレー",shop:"マジックスパイス",coords:[141.35,43.07]},
  {key:"北海道石狩鍋",pref:"北海道",city:"石狩市",food:"石狩鍋",shop:"金大亭",coords:[141.30,43.20]},
  {key:"北海道海鮮丼",pref:"北海道",city:"小樽市",food:"海鮮丼（ウニ・イクラ）",shop:"うにむらかみ",coords:[141.00,43.18]},
  {key:"青森せんべい汁",pref:"青森県",city:"八戸市",food:"せんべい汁",shop:"みなと食堂",coords:[141.48,40.51]},
  {key:"青森いちご煮",pref:"青森県",city:"八戸市",food:"いちご煮",shop:"割烹 銀波",coords:[141.49,40.52]},
  {key:"青森十和田バラ焼き",pref:"青森県",city:"十和田市",food:"十和田バラ焼き",shop:"司バラ焼き大衆食堂",coords:[141.20,40.61]},
  {key:"岩手わんこそば",pref:"岩手県",city:"盛岡市",food:"わんこそば",shop:"東家",coords:[141.15,39.70]},
  {key:"岩手盛岡冷麺",pref:"岩手県",city:"盛岡市",food:"盛岡冷麺",shop:"ぴょんぴょん舎",coords:[141.16,39.71]},
  {key:"岩手盛岡じゃじゃ麺",pref:"岩手県",city:"盛岡市",food:"盛岡じゃじゃ麺",shop:"白龍",coords:[141.17,39.69]},
  {key:"宮城牛タン",pref:"宮城県",city:"仙台市",food:"牛タン焼き",shop:"たんや善治郎",coords:[140.87,38.27]},
  {key:"宮城ずんだ餅",pref:"宮城県",city:"仙台市",food:"ずんだ餅",shop:"ずんだ茶寮",coords:[140.88,38.28]},
  {key:"宮城はらこ飯",pref:"宮城県",city:"亘理町",food:"はらこ飯",shop:"田園",coords:[140.85,38.03]},
  {key:"秋田きりたんぽ",pref:"秋田県",city:"秋田市",food:"きりたんぽ鍋",shop:"濱乃家",coords:[140.10,39.72]},
  {key:"秋田稲庭うどん",pref:"秋田県",city:"湯沢市",food:"稲庭うどん",shop:"佐藤養助",coords:[140.50,39.17]},
  {key:"秋田いぶりがっこ",pref:"秋田県",city:"秋田市",food:"いぶりがっこ",shop:"桜食品",coords:[140.11,39.73]},
  {key:"山形芋煮",pref:"山形県",city:"山形市",food:"芋煮",shop:"後藤屋",coords:[140.35,38.25]},
  {key:"山形米沢牛",pref:"山形県",city:"米沢市",food:"米沢牛",shop:"登起波",coords:[140.12,37.92]},
  {key:"山形板そば",pref:"山形県",city:"山形市",food:"板そば",shop:"そば処 三津屋",coords:[140.36,38.26]},
  {key:"福島喜多方ラーメン",pref:"福島県",city:"喜多方市",food:"喜多方ラーメン",shop:"坂内食堂",coords:[139.88,37.65]},
  {key:"福島なみえ焼そば",pref:"福島県",city:"浪江町",food:"なみえ焼そば",shop:"杉乃家",coords:[141.00,37.48]},
  {key:"福島円盤餃子",pref:"福島県",city:"福島市",food:"円盤餃子",shop:"餃子 照井",coords:[140.47,37.75]},
  {key:"茨城あんこう鍋",pref:"茨城県",city:"北茨城市",food:"あんこう鍋",shop:"山翠",coords:[140.77,36.83]},
  {key:"茨城水戸納豆",pref:"茨城県",city:"水戸市",food:"水戸納豆",shop:"天狗納豆",coords:[140.45,36.37]},
  {key:"茨城常陸牛",pref:"茨城県",city:"水戸市",food:"常陸牛",shop:"肉のイイジマ",coords:[140.46,36.38]},
  {key:"栃木宇都宮餃子",pref:"栃木県",city:"宇都宮市",food:"宇都宮餃子",shop:"宇都宮みんみん",coords:[139.88,36.55]},
  {key:"栃木佐野ラーメン",pref:"栃木県",city:"佐野市",food:"佐野ラーメン",shop:"日向屋",coords:[139.58,36.32]},
  {key:"栃木しもつかれ",pref:"栃木県",city:"宇都宮市",food:"しもつかれ",shop:"藤井商店",coords:[139.89,36.56]},
  {key:"群馬おきりこみ",pref:"群馬県",city:"前橋市",food:"おきりこみ",shop:"新田乃庄",coords:[139.07,36.38]},
  {key:"群馬焼きまんじゅう",pref:"群馬県",city:"前橋市",food:"焼きまんじゅう",shop:"原嶋屋総本家",coords:[139.08,36.39]},
  {key:"群馬水沢うどん",pref:"群馬県",city:"渋川市",food:"水沢うどん",shop:"田丸屋",coords:[138.98,36.55]},
  {key:"埼玉冷汁うどん",pref:"埼玉県",city:"さいたま市",food:"冷汁うどん",shop:"わっしょい",coords:[139.65,35.85]},
  {key:"埼玉草加せんべい",pref:"埼玉県",city:"草加市",food:"草加せんべい",shop:"山香煎餅本舗",coords:[139.80,35.82]},
  {key:"埼玉ゼリーフライ",pref:"埼玉県",city:"行田市",food:"ゼリーフライ",shop:"駒形屋",coords:[139.45,36.13]},
  {key:"千葉なめろう",pref:"千葉県",city:"南房総市",food:"なめろう",shop:"だいぼ",coords:[139.85,35.03]},
  {key:"千葉勝浦タンタンメン",pref:"千葉県",city:"勝浦市",food:"勝浦タンタンメン",shop:"江ざわ",coords:[140.13,35.15]},
  {key:"千葉落花生",pref:"千葉県",city:"八街市",food:"落花生料理",shop:"ますだの落花生",coords:[140.32,35.65]},
  {key:"東京もんじゃ焼き",pref:"東京都",city:"中央区",food:"もんじゃ焼き",shop:"月島もんじゃ 近どう",coords:[139.78,35.67]},
  {key:"東京江戸前寿司",pref:"東京都",city:"中央区",food:"江戸前寿司",shop:"銀座 寿司幸本店",coords:[139.77,35.67]},
  {key:"東京深川飯",pref:"東京都",city:"江東区",food:"深川飯",shop:"深川宿",coords:[139.82,35.67]},
  {key:"神奈川家系ラーメン",pref:"神奈川県",city:"横浜市",food:"横浜家系ラーメン",shop:"吉村家",coords:[139.65,35.45]},
  {key:"神奈川しらす丼",pref:"神奈川県",city:"鎌倉市",food:"しらす丼",shop:"とびっちょ",coords:[139.55,35.32]},
  {key:"神奈川海軍カレー",pref:"神奈川県",city:"横須賀市",food:"よこすか海軍カレー",shop:"ウッドアイランド",coords:[139.67,35.28]},
  {key:"新潟へぎそば",pref:"新潟県",city:"十日町市",food:"へぎそば",shop:"小嶋屋総本店",coords:[138.75,37.13]},
  {key:"新潟タレかつ丼",pref:"新潟県",city:"新潟市",food:"タレかつ丼",shop:"とんかつ太郎",coords:[139.05,37.92]},
  {key:"新潟笹だんご",pref:"新潟県",city:"新潟市",food:"笹だんご",shop:"田中屋本店",coords:[139.06,37.93]},
  {key:"富山ブラックラーメン",pref:"富山県",city:"富山市",food:"富山ブラックラーメン",shop:"西町大喜",coords:[137.22,36.70]},
  {key:"富山白えび",pref:"富山県",city:"富山市",food:"白えび料理",shop:"白えび亭",coords:[137.23,36.71]},
  {key:"富山ます寿し",pref:"富山県",city:"富山市",food:"ます寿し",shop:"ますのすし本舗 源",coords:[137.21,36.69]},
  {key:"石川金沢カレー",pref:"石川県",city:"金沢市",food:"金沢カレー",shop:"カレーのチャンピオン",coords:[136.63,36.57]},
  {key:"石川治部煮",pref:"石川県",city:"金沢市",food:"治部煮",shop:"加賀料理 大志満",coords:[136.64,36.58]},
  {key:"石川ハントンライス",pref:"石川県",city:"金沢市",food:"ハントンライス",shop:"グリルオーツカ",coords:[136.62,36.56]},
  {key:"福井越前おろしそば",pref:"福井県",city:"越前市",food:"越前おろしそば",shop:"越前そばの里",coords:[136.17,35.90]},
  {key:"福井ソースカツ丼",pref:"福井県",city:"福井市",food:"ソースカツ丼",shop:"ヨーロッパ軒",coords:[136.22,36.07]},
  {key:"福井へしこ",pref:"福井県",city:"小浜市",food:"へしこ",shop:"千鳥苑",coords:[135.75,35.50]},
  {key:"山梨ほうとう",pref:"山梨県",city:"富士吉田市",food:"ほうとう",shop:"ほうとう不動",coords:[138.80,35.47]},
  {key:"山梨吉田うどん",pref:"山梨県",city:"富士吉田市",food:"吉田のうどん",shop:"麺許皆伝",coords:[138.81,35.48]},
  {key:"山梨甲府鳥もつ煮",pref:"山梨県",city:"甲府市",food:"甲府鳥もつ煮",shop:"奥藤本店",coords:[138.57,35.67]},
  {key:"長野信州そば",pref:"長野県",city:"長野市",food:"信州そば",shop:"戸隠そば 山口屋",coords:[138.18,36.65]},
  {key:"長野おやき",pref:"長野県",city:"長野市",food:"おやき",shop:"小川の庄 おやき村",coords:[138.19,36.66]},
  {key:"長野ソースかつ丼",pref:"長野県",city:"駒ヶ根市",food:"駒ヶ根ソースかつ丼",shop:"明治亭",coords:[137.97,35.73]},
  {key:"岐阜飛騨牛",pref:"岐阜県",city:"高山市",food:"飛騨牛ステーキ",shop:"キッチン飛騨",coords:[137.25,36.15]},
  {key:"岐阜朴葉味噌",pref:"岐阜県",city:"高山市",food:"朴葉味噌",shop:"飛騨 匠の館",coords:[137.26,36.16]},
  {key:"岐阜鶏ちゃん",pref:"岐阜県",city:"下呂市",food:"鶏ちゃん",shop:"杉の子",coords:[137.25,35.80]},
  {key:"静岡富士宮やきそば",pref:"静岡県",city:"富士宮市",food:"富士宮やきそば",shop:"富士宮やきそば学会",coords:[138.62,35.22]},
  {key:"静岡浜松餃子",pref:"静岡県",city:"浜松市",food:"浜松餃子",shop:"石松餃子",coords:[137.73,34.72]},
  {key:"静岡おでん",pref:"静岡県",city:"静岡市",food:"静岡おでん",shop:"三河屋",coords:[138.38,34.97]},
  {key:"愛知ひつまぶし",pref:"愛知県",city:"名古屋市",food:"ひつまぶし",shop:"あつた蓬莱軒",coords:[136.90,35.07]},
  {key:"愛知味噌カツ",pref:"愛知県",city:"名古屋市",food:"味噌カツ",shop:"矢場とん",coords:[136.91,35.17]},
  {key:"愛知手羽先",pref:"愛知県",city:"名古屋市",food:"手羽先唐揚げ",shop:"世界の山ちゃん",coords:[136.89,35.17]},
  {key:"愛知味噌煮込みうどん",pref:"愛知県",city:"名古屋市",food:"味噌煮込みうどん",shop:"山本屋総本家",coords:[136.90,35.16]},
  {key:"三重松阪牛",pref:"三重県",city:"松阪市",food:"松阪牛ステーキ",shop:"和田金",coords:[136.53,34.58]},
  {key:"三重伊勢うどん",pref:"三重県",city:"伊勢市",food:"伊勢うどん",shop:"ふくすけ",coords:[136.72,34.48]},
  {key:"三重てこね寿司",pref:"三重県",city:"伊勢市",food:"てこね寿司",shop:"すし久",coords:[136.73,34.49]},
  {key:"滋賀近江牛",pref:"滋賀県",city:"近江八幡市",food:"近江牛",shop:"せんなり亭 伽羅",coords:[136.10,35.13]},
  {key:"滋賀ふなずし",pref:"滋賀県",city:"高島市",food:"ふなずし",shop:"魚治",coords:[136.03,35.35]},
  {key:"滋賀焼き鯖そうめん",pref:"滋賀県",city:"木之本",food:"焼き鯖そうめん",shop:"翼果楼",coords:[136.17,35.47]},
  {key:"京都湯豆腐",pref:"京都府",city:"京都市",food:"湯豆腐",shop:"南禅寺 順正",coords:[135.78,35.02]},
  {key:"京都漬物",pref:"京都府",city:"京都市",food:"京漬物",shop:"西利",coords:[135.77,34.98]},
  {key:"京都おばんざい",pref:"京都府",city:"京都市",food:"おばんざい",shop:"京菜味のむら",coords:[135.76,34.99]},
  {key:"大阪たこ焼き",pref:"大阪府",city:"大阪市",food:"たこ焼き",shop:"たこやき道楽 わなか",coords:[135.50,34.67]},
  {key:"大阪お好み焼き",pref:"大阪府",city:"大阪市",food:"お好み焼き",shop:"きじ",coords:[135.51,34.70]},
  {key:"大阪串カツ",pref:"大阪府",city:"大阪市",food:"串カツ",shop:"串かつ だるま",coords:[135.50,34.65]},
  {key:"兵庫神戸牛",pref:"兵庫県",city:"神戸市",food:"神戸牛",shop:"モーリヤ",coords:[135.18,34.68]},
  {key:"兵庫明石焼き",pref:"兵庫県",city:"明石市",food:"明石焼き",shop:"本家きむらや",coords:[135.00,34.65]},
  {key:"兵庫ぼっかけ",pref:"兵庫県",city:"神戸市",food:"ぼっかけうどん",shop:"長田本庄軒",coords:[135.13,34.64]},
  {key:"奈良柿の葉ずし",pref:"奈良県",city:"吉野町",food:"柿の葉ずし",shop:"柿の葉すし本舗たなか",coords:[135.87,34.40]},
  {key:"奈良三輪そうめん",pref:"奈良県",city:"桜井市",food:"三輪そうめん",shop:"池利",coords:[135.85,34.52]},
  {key:"奈良茶粥",pref:"奈良県",city:"奈良市",food:"茶粥",shop:"塔の茶屋",coords:[135.83,34.68]},
  {key:"和歌山ラーメン",desc:"濃厚な豚骨醤油。早寿司と一緒に食べるのが流儀。",pref:"和歌山県",city:"和歌山市",food:"和歌山ラーメン",shop:"井出商店",coords:[135.17,34.22]},
  {key:"和歌山めはり寿司",pref:"和歌山県",city:"新宮市",food:"めはり寿司",shop:"総本家めはりや",coords:[135.98,33.72]},
  {key:"和歌山梅干し",pref:"和歌山県",city:"みなべ町",food:"紀州梅干し",shop:"中田食品",coords:[135.33,33.77]},
  {key:"鳥取松葉がに",pref:"鳥取県",city:"鳥取市",food:"松葉がに",shop:"かに吉",coords:[134.23,35.50]},
  {key:"鳥取牛骨ラーメン",desc:"牛骨特有の甘みと香ばしさがある、希少な一杯。",pref:"鳥取県",city:"鳥取市",food:"鳥取牛骨ラーメン",shop:"香味徳",coords:[134.23,35.50]},
  {key:"鳥取大山どり",pref:"鳥取県",city:"鳥取市",food:"大山どり料理",shop:"強小亭",coords:[134.24,35.51]},
  {key:"島根出雲そば",pref:"島根県",city:"出雲市",food:"出雲そば",shop:"羽根屋",coords:[132.77,35.37]},
  {key:"島根しじみ汁",pref:"島根県",city:"松江市",food:"しじみ汁",shop:"しじみ茶屋",coords:[133.05,35.47]},
  {key:"島根鯛めし",pref:"島根県",city:"松江市",food:"鯛めし",shop:"皆美館",coords:[133.06,35.48]},
  {key:"岡山デミカツ丼",pref:"岡山県",city:"岡山市",food:"デミカツ丼",shop:"味司 野村",coords:[133.93,34.65]},
  {key:"岡山カキオコ",pref:"岡山県",city:"備前市",food:"岡山カキオコ",shop:"タマちゃん",coords:[134.18,34.73]},
  {key:"岡山ホルモンうどん",pref:"岡山県",city:"津山市",food:"ホルモンうどん",shop:"橋野食堂",coords:[133.78,35.07]},
  {key:"広島お好み焼き",pref:"広島県",city:"広島市",food:"広島風お好み焼き",shop:"みっちゃん総本店",coords:[132.45,34.38]},
  {key:"広島牡蠣",pref:"広島県",city:"廿日市市",food:"牡蠣料理",shop:"かき船 かなわ",coords:[132.32,34.28]},
  {key:"広島あなご飯",pref:"広島県",city:"廿日市市",food:"穴子飯",shop:"うえの",coords:[132.33,34.29]},
  {key:"山口ふぐ",pref:"山口県",city:"下関市",food:"ふぐ料理",shop:"春帆楼",coords:[130.95,33.95]},
  {key:"山口瓦そば",pref:"山口県",city:"下関市",food:"瓦そば",shop:"元祖瓦そば たかせ",coords:[130.96,33.96]},
  {key:"山口バリそば",pref:"山口県",city:"下関市",food:"バリそば",shop:"春来軒",coords:[130.94,33.94]},
  {key:"徳島ラーメン",desc:"甘辛い豚バラ肉と生卵。ご飯との相性が最高。",pref:"徳島県",city:"徳島市",food:"徳島ラーメン",shop:"いのたに",coords:[134.55,34.07]},
  {key:"徳島阿波尾鶏",pref:"徳島県",city:"徳島市",food:"阿波尾鶏",shop:"一鴻",coords:[134.56,34.08]},
  {key:"徳島すだち",pref:"徳島県",city:"徳島市",food:"すだち料理",shop:"割烹 濱伊",coords:[134.54,34.06]},
  {key:"香川讃岐うどん",pref:"香川県",city:"綾川町",food:"讃岐うどん",shop:"山越うどん",coords:[133.90,34.22]},
  {key:"香川骨付鳥",pref:"香川県",city:"丸亀市",food:"骨付鳥",shop:"一鶴",coords:[133.80,34.28]},
  {key:"香川しょうゆ豆",pref:"香川県",city:"高松市",food:"しょうゆ豆",shop:"豆匠 むらき",coords:[134.05,34.35]},
  {key:"愛媛宇和島鯛めし",pref:"愛媛県",city:"宇和島市",food:"宇和島鯛めし",shop:"ほづみ亭",coords:[132.57,33.22]},
  {key:"愛媛じゃこ天",pref:"愛媛県",city:"宇和島市",food:"じゃこ天",shop:"谷本蒲鉾店",coords:[132.58,33.23]},
  {key:"愛媛今治焼鳥",pref:"愛媛県",city:"今治市",food:"今治焼鳥",shop:"五味鳥",coords:[133.00,34.07]},
  {key:"高知カツオたたき",pref:"高知県",city:"高知市",food:"カツオのたたき",shop:"明神丸",coords:[133.55,33.55]},
  {key:"高知鍋焼きラーメン",pref:"高知県",city:"須崎市",food:"鍋焼きラーメン",shop:"橋本食堂",coords:[133.28,33.40]},
  {key:"高知皿鉢料理",pref:"高知県",city:"高知市",food:"皿鉢料理",shop:"司",coords:[133.56,33.56]},
  {key:"福岡博多ラーメン",pref:"福岡県",city:"福岡市",food:"博多ラーメン",shop:"一風堂",coords:[130.40,33.58]},
  {key:"福岡もつ鍋",pref:"福岡県",city:"福岡市",food:"もつ鍋",shop:"やま中",coords:[130.41,33.60]},
  {key:"福岡水炊き",pref:"福岡県",city:"福岡市",food:"水炊き",shop:"華味鳥",coords:[130.39,33.60]},
  {key:"福岡辛子明太子",pref:"福岡県",city:"福岡市",food:"辛子明太子",shop:"ふくや",coords:[130.42,33.61]},
  {key:"佐賀呼子いか",pref:"佐賀県",city:"唐津市",food:"呼子のいか",shop:"河太郎",coords:[129.87,33.52]},
  {key:"佐賀牛",pref:"佐賀県",city:"佐賀市",food:"佐賀牛",shop:"季楽",coords:[130.30,33.25]},
  {key:"佐賀シシリアンライス",pref:"佐賀県",city:"佐賀市",food:"シシリアンライス",shop:"白山文雅",coords:[130.31,33.26]},
  {key:"長崎ちゃんぽん",pref:"長崎県",city:"長崎市",food:"ちゃんぽん",shop:"四海樓",coords:[129.87,32.75]},
  {key:"長崎皿うどん",pref:"長崎県",city:"長崎市",food:"皿うどん",shop:"江山楼",coords:[129.88,32.76]},
  {key:"長崎佐世保バーガー",pref:"長崎県",city:"佐世保市",food:"佐世保バーガー",shop:"ヒカリ",coords:[129.72,33.17]},
  {key:"長崎カステラ",pref:"長崎県",city:"長崎市",food:"カステラ",shop:"福砂屋",coords:[129.86,32.74]},
  {key:"熊本馬刺し",pref:"熊本県",city:"熊本市",food:"馬刺し",shop:"菅乃屋",coords:[130.70,32.80]},
  {key:"熊本太平燕",pref:"熊本県",city:"熊本市",food:"太平燕",shop:"紅蘭亭",coords:[130.71,32.81]},
  {key:"熊本からし蓮根",pref:"熊本県",city:"熊本市",food:"からし蓮根",shop:"森からし蓮根",coords:[130.69,32.79]},
  {key:"大分とり天",pref:"大分県",city:"大分市",food:"とり天",shop:"東洋軒",coords:[131.60,33.23]},
  {key:"大分中津からあげ",pref:"大分県",city:"中津市",food:"中津からあげ",shop:"森山",coords:[131.18,33.60]},
  {key:"大分だんご汁",pref:"大分県",city:"大分市",food:"だんご汁",shop:"甘味茶屋",coords:[131.61,33.24]},
  {key:"宮崎チキン南蛮",pref:"宮崎県",city:"延岡市",food:"チキン南蛮",shop:"おぐら",coords:[131.67,32.58]},
  {key:"宮崎地鶏炭火焼",pref:"宮崎県",city:"宮崎市",food:"地鶏炭火焼",shop:"ぐんけい",coords:[131.42,31.90]},
  {key:"宮崎肉巻きおにぎり",pref:"宮崎県",city:"宮崎市",food:"肉巻きおにぎり",shop:"本家宮崎肉巻きおにぎり",coords:[131.43,31.91]},
  {key:"鹿児島黒豚しゃぶ",pref:"鹿児島県",city:"鹿児島市",food:"黒豚しゃぶしゃぶ",shop:"あじもり",coords:[130.55,31.60]},
  {key:"鹿児島鶏飯",pref:"鹿児島県",city:"奄美市",food:"鶏飯",shop:"みなとや",coords:[129.48,28.38]},
  {key:"鹿児島白くま",pref:"鹿児島県",city:"鹿児島市",food:"白くま",shop:"天文館むじゃき",coords:[130.56,31.61]},
  {key:"沖縄ゴーヤチャンプルー",pref:"沖縄県",city:"那覇市",food:"ゴーヤチャンプルー",shop:"ゆうなんぎい",coords:[127.68,26.22]},
  {key:"沖縄そば",pref:"沖縄県",city:"本部町",food:"沖縄そば",shop:"きしもと食堂",coords:[127.98,26.63]},
  {key:"沖縄タコライス",pref:"沖縄県",city:"金武町",food:"タコライス",shop:"キングタコス",coords:[127.72,26.48]},
  {key:"沖縄ラフテー",pref:"沖縄県",city:"那覇市",food:"ラフテー",shop:"琉球料理 美榮",coords:[127.69,26.23]},
];

const RAMEN_DATA = [
  {key:"札幌味噌ラーメン",desc:"濃厚味噌とラードの膜、黄色いちぢれ麺の王道。",pref:"北海道",city:"札幌市",food:"札幌味噌",shop:"すみれ",coords:[141.35,43.06]},
  {key:"旭川醤油ラーメン",desc:"魚介×豚骨のダブルスープに焦がしラードのコク。",pref:"北海道",city:"旭川市",food:"旭川醤油",shop:"蜂屋",coords:[142.37,43.77]},
  {key:"函館塩ラーメン",desc:"透明感あふれる澄んだ塩味。函館の歴史の味。",pref:"北海道",city:"函館市",food:"函館塩",shop:"あじさい",coords:[140.73,41.77]},
  {key:"室蘭カレーラーメン",desc:"濃厚でスパイシーなカレー味。北海道第4の勢力。",pref:"北海道",city:"室蘭市",food:"室蘭カレー",shop:"味の大王",coords:[140.97,42.32]},
  {key:"津軽煮干しラーメン",desc:"煮干しの旨味が凝縮された、酸味とコクのあるスープ。",pref:"青森県",city:"青森市",food:"津軽煮干し",shop:"たかはし中華そば店",coords:[140.74,40.82]},
  {key:"味噌カレー牛乳ラーメン",desc:"味噌、カレー、牛乳、バターが融合した驚きの旨さ。",pref:"青森県",city:"青森市",food:"味噌カレー牛乳",shop:"味の札幌 大西",coords:[140.74,40.83]},
  {key:"赤湯からみそラーメン",desc:"刺激的な辛味噌を溶かして食べる、山形の代名詞。",pref:"山形県",city:"南陽市",food:"赤湯からみそ",shop:"龍上海",coords:[140.17,38.05]},
  {key:"酒田ワンタン麺",desc:"極薄のふわふわワンタンと、上品な魚介ダシ。",pref:"山形県",city:"酒田市",food:"酒田ワンタン麺",shop:"満月",coords:[139.83,38.92]},
  {key:"山形冷やしラーメン",desc:"蕎麦屋発祥。氷が浮いても脂が固まらない工夫。",pref:"山形県",city:"山形市",food:"山形冷やし",shop:"栄屋本店",coords:[140.35,38.25]},
  {key:"米沢ラーメン",desc:"超極細の手揉みちぢれ麺と、あっさり醤油。",pref:"山形県",city:"米沢市",food:"米沢ラーメン",shop:"そばの店 ひらま",coords:[140.12,37.92]},
  {key:"喜多方ラーメン",desc:"日本三大ラーメン。平打ち多加水麺の食感が魅力。",pref:"福島県",city:"喜多方市",food:"喜多方",shop:"坂内食堂",coords:[139.88,37.65]},
  {key:"白河ラーメン",desc:"手打ち麺と、炭火焼きチャーシューの薫香。",pref:"福島県",city:"白河市",food:"白河ラーメン",shop:"とら食堂",coords:[140.18,37.13]},
  {key:"佐野ラーメン",desc:"青竹打ちの不揃いな麺が、透明なスープに合う。",pref:"栃木県",city:"佐野市",food:"佐野",shop:"日向屋",coords:[139.58,36.32]},
  {key:"スタミナラーメン",desc:"レバーやカボチャが入った甘辛い餡が熱々。",pref:"茨城県",city:"水戸市",food:"スタミナラーメン",shop:"がむしゃ",coords:[140.45,36.37]},
  {key:"藤岡ラーメン",desc:"強いコシの極太手打ち麺が特徴。",pref:"群馬県",city:"藤岡市",food:"藤岡ラーメン",shop:"みやご食堂",coords:[139.07,36.25]},
  {key:"勝浦タンタンメン",desc:"ラー油と玉ねぎが主役。ゴマを使わないタンタン。",pref:"千葉県",city:"勝浦市",food:"勝浦タンタン",shop:"江ざわ",coords:[140.13,35.15]},
  {key:"竹岡式ラーメン",desc:"チャーシューの煮汁をお湯で割る、漁師町の味。",pref:"千葉県",city:"富津市",food:"竹岡式",shop:"梅乃家",coords:[139.87,35.27]},
  {key:"アリランラーメン",desc:"ニンニク・ニラ・玉ねぎが強烈な秘境ラーメン。",pref:"千葉県",city:"夷隅郡",food:"アリラン",shop:"八平の食堂",coords:[140.27,35.27]},
  {key:"八王子ラーメン",desc:"醤油ベースのスープに、シャキシャキの刻み玉ねぎ。",pref:"東京都",city:"八王子市",food:"八王子ラーメン",shop:"吾衛門",coords:[139.32,35.65]},
  {key:"横浜家系ラーメン",desc:"濃厚豚骨醤油、鶏油、ほうれん草。ガツンとくる。",pref:"神奈川県",city:"横浜市",food:"横浜家系",shop:"吉村家",coords:[139.65,35.45]},
  {key:"サンマーメン",desc:"横浜発祥。醤油スープにモヤシ主体のあんかけ。",pref:"神奈川県",city:"横浜市",food:"サンマーメン",shop:"玉泉亭",coords:[139.65,35.44]},
  {key:"燕三条背脂ラーメン",desc:"煮干しスープを覆う大量の背脂と極太麺。",pref:"新潟県",city:"燕市",food:"燕三条背脂",shop:"杭州飯店",coords:[138.88,37.67]},
  {key:"長岡生姜醤油ラーメン",desc:"濃口醤油に生姜を効かせた、体が温まる雪国の味。",pref:"新潟県",city:"長岡市",food:"長岡生姜醤油",shop:"青島食堂",coords:[138.85,37.45]},
  {key:"新潟濃厚味噌ラーメン",desc:"割りスープで自分好みの濃さに薄めて食べるスタイル。",pref:"新潟県",city:"新潟市",food:"新潟濃厚味噌",shop:"こまどり",coords:[139.05,37.92]},
  {key:"富山ブラックラーメン",desc:"労働者のための、真っ黒で塩辛い「おかず」スープ。",pref:"富山県",city:"富山市",food:"富山ブラック",shop:"西町大喜",coords:[137.22,36.70]},
  {key:"高山ラーメン",desc:"鶏ガラベースのあっさり醤油。スープを一緒に煮出す。",pref:"岐阜県",city:"高山市",food:"高山ラーメン",shop:"角や",coords:[137.25,36.15]},
  {key:"台湾ラーメン",desc:"名古屋発祥。激辛ミンチとニンニクが癖になる。",pref:"愛知県",city:"名古屋市",food:"台湾ラーメン",shop:"味仙",coords:[136.90,35.17]},
  {key:"天理ラーメン",desc:"白菜たっぷりのニンニクが効いた醤油ベース。",pref:"奈良県",city:"天理市",food:"天理ラーメン",shop:"彩華ラーメン",coords:[135.83,34.60]},
  {key:"京都ラーメン",desc:"見た目は真っ黒、味は香ばしくコクのある醤油。",pref:"京都府",city:"京都市",food:"京都ラーメン",shop:"新福菜館",coords:[135.77,34.98]},
  {key:"和歌山ラーメン",desc:"濃厚な豚骨醤油。早寿司と一緒に食べるのが流儀。",pref:"和歌山県",city:"和歌山市",food:"和歌山ラーメン",shop:"井出商店",coords:[135.17,34.22]},
  {key:"播州ラーメン",desc:"醤油ベースで、甘みが強い独特のスープが特徴。",pref:"兵庫県",city:"西脇市",food:"播州ラーメン",shop:"西脇大橋ラーメン",coords:[134.97,34.98]},
  {key:"鳥取牛骨ラーメン",desc:"牛骨特有の甘みと香ばしさがある、希少な一杯。",pref:"鳥取県",city:"鳥取市",food:"鳥取牛骨",shop:"香味徳",coords:[134.23,35.50]},
  {key:"笠岡ラーメン",desc:"親鳥の「煮鶏」を載せる、鶏100%の醤油味。",pref:"岡山県",city:"笠岡市",food:"笠岡ラーメン",shop:"坂本",coords:[133.50,34.50]},
  {key:"尾道ラーメン",desc:"鶏ガラ醤油に浮く、大粒の背脂ミンチが決め手。",pref:"広島県",city:"尾道市",food:"尾道ラーメン",shop:"朱",coords:[133.20,34.40]},
  {key:"徳島ラーメン",desc:"甘辛い豚バラ肉と生卵。ご飯との相性が最高。",pref:"徳島県",city:"徳島市",food:"徳島ラーメン",shop:"いのたに",coords:[134.55,34.07]},
  {key:"鍋焼きラーメン",desc:"須崎市名物。土鍋で提供される鶏ガラ醤油味。",pref:"高知県",city:"須崎市",food:"鍋焼きラーメン",shop:"橋本食堂",coords:[133.28,33.40]},
  {key:"博多ラーメン",desc:"極細麺の替え玉文化。全国で最も有名な豚骨。",pref:"福岡県",city:"福岡市",food:"博多ラーメン",shop:"一風堂",coords:[130.40,33.58]},
  {key:"久留米ラーメン",desc:"豚骨発祥の地。濃厚でコクのある「呼び戻し」。",pref:"福岡県",city:"久留米市",food:"久留米ラーメン",shop:"清陽軒",coords:[130.52,33.32]},
  {key:"熊本ラーメン",desc:"マー油（焦がしニンニク油）の香ばしさが特徴。",pref:"熊本県",city:"熊本市",food:"熊本ラーメン",shop:"こむらさき",coords:[130.70,32.80]},
  {key:"鹿児島ラーメン",desc:"鶏ガラと豚骨。漬物がセットで出てくる優しい味。",pref:"鹿児島県",city:"鹿児島市",food:"鹿児島ラーメン",shop:"くろいわ",coords:[130.55,31.60]},
];
